routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('/home');
});


Auth::routes();
Route::group(['middleware' => 'auth'], function () {

    Route::get('/home', 'HomeController@index')->name('home');

    Route::get('stores/{id}/sale_accept', 'StoreController@saleAccept')->name('stores.sale_accept');
    Route::get('stores/{id}/control_accept', 'StoreController@controlAccept')->name('stores.control_accept');
    Route::get('stores/{id}/notify_mms', 'StoreController@notifyMMS')->name('stores.notify_mms');
    Route::get('stores/{id}/retry_mms', 'StoreController@retryMMS')->name('stores.retry_mms');
    Route::get('stores/{id}/reject', 'StoreController@reject')->name('stores.reject');
    Route::get('stores/{id}/reopen_upload_document', 'StoreController@reopenUploadDocument')->name('stores.reopen');
    Route::post('stores/updateStore/{id}', 'StoreController@updateStore')->name('stores.updateStore');
    Route::post('stores/updateContract/{id}', 'StoreController@updateContract')->name('stores.updateContract');
    Route::post('stores/reUploadContract/{id}', 'StoreController@reUploadContract')->name('stores.reUploadContract');
    Route::post('stores/saleAction/{id}', 'StoreController@saleAction')->name('stores.saleAction');
    Route::post('stores/controlAction/{id}', 'StoreController@controlAction')->name('stores.controlAction');
    Route::post('stores/sendRequest/{id}', 'StoreController@sendRequest')->name('stores.sendRequest');
    Route::post('stores/lockMerchant', 'StoreController@lockMerchant')->name('stores.lockMerchant');
    Route::post('stores/unlockMerchant', 'StoreController@unlockMerchant')->name('stores.unlockMerchant');

    Route::get('stores/needApproveList', 'StoreController@needApproveList')->name('stores.needApproveList');
    Route::get('stores/activeList', 'StoreController@activeList')->name('stores.activeList');
    Route::get('stores/registerList', 'StoreController@registerList')->name('stores.registerList');
    Route::get('stores/approvedList', 'StoreController@approvedList')->name('stores.approvedList');
    Route::get('stores/deniedList', 'StoreController@deniedList')->name('stores.deniedList');
    Route::get('stores/lockedList', 'StoreController@lockedList')->name('stores.lockedList');
    Route::resource('stores', 'StoreController')->middleware('auth');

    Route::resource('trials', 'TrialController');


    Route::post('terminals/{id}/reject', 'TerminalController@reject')->name('terminals.reject');
    Route::get('terminals/{id}/approve', 'TerminalController@approve')->name('terminals.approve');
    Route::get('terminals/{id}/sendRequest', 'TerminalController@sendRequest')->name('terminals.sendRequest');
    Route::get('terminals/{id}/showFirstTerminal', 'TerminalController@showFirstTerminal')->name('terminals.showFirstTerminal');
    Route::get('terminals/{id}/editFirstTerminal', 'TerminalController@editFirstTerminal')->name('terminals.editFirstTerminal');
    Route::patch('terminals/updateFirstTerminal/{id}', 'TerminalController@updateFirstTerminal')->name('terminals.updateFirstTerminal');
    Route::get('terminals/needApproveList', 'TerminalController@needApproveList')->name('terminals.needApproveList');
    Route::get('terminals/approvedList', 'TerminalController@approvedList')->name('terminals.approvedList');
    Route::get('terminals/deniedList', 'TerminalController@deniedList')->name('terminals.deniedList');
    Route::get('terminals/lockedList', 'TerminalController@lockedList')->name('terminals.lockedList');
    Route::get('terminals/ajaxListMerchant', 'TerminalController@ajaxListMerchant')->name('terminals.ajaxListMerchant');
    Route::get('terminals/ajaxListMerchantWithAll', 'TerminalController@ajaxListMerchantWithAll')->name('terminals.ajaxListMerchantWithAll');
    Route::get('terminals/ajaxListTerminalByMerchantCode', 'TerminalController@ajaxListTerminalByMerchantCode')->name('terminals.ajaxListTerminalByMerchantCode');

    Route::get('terminals/ajaxFindBankAccount', 'TerminalController@ajaxFindBankAccount')->name('terminals.ajaxFindBankAccount');
    Route::post('stores/lockTerminal', 'TerminalController@lockTerminal')->name('terminals.lockTerminal');
    Route::post('stores/unlockTerminal', 'TerminalController@unlockTerminal')->name('terminals.unlockTerminal');

    Route::resource('terminals', 'TerminalController')->middleware('auth');

    Route::resource('terminalBatches', 'MpTerminalBatchController')->middleware('auth');
    Route::post('terminalBatches/{id}/reject', 'MpTerminalBatchController@reject')->name('terminalBatches.reject');
    Route::get('terminalBatches/{id}/approve', 'MpTerminalBatchController@approve')->name('terminalBatches.approve');
    Route::get('terminalBatches/{id}/reopenForEditTerminals', 'MpTerminalBatchController@reopenForEditTerminals')
        ->name('terminalBatches.reopenForEditTerminals');

    // enjoyments
    Route::get('enjoyments/changeEnjoyment', 'EnjoymentsController@changeEnjoyment')->name('enjoyments.changeEnjoyment');
    Route::get('enjoyments/index', 'EnjoymentsController@index')->name('enjoyments.index');
    Route::get('enjoyments/chooseMerchant', 'EnjoymentsController@chooseMerchant')->name('enjoyments.chooseMerchant');
    Route::post('enjoyments/chooseMerchant', 'EnjoymentsController@chooseMerchant')->name('enjoyments.chooseMerchant');
    Route::post('enjoyments/upsertEnjoyment', 'EnjoymentsController@upsertEnjoyment')->name('enjoyments.upsertEnjoyment');
    Route::get('enjoyments/ajaxFindBankAccount', 'EnjoymentsController@ajaxFindBankAccount')->name('enjoyments.ajaxFindBankAccount');
    Route::resource('enjoyments', 'EnjoymentsController')->middleware('auth');

    Route::resource('smsLogs', 'SmsLogController')->middleware('auth');

    Route::resource('users', 'UserController');

    Route::resource('roles', 'RoleController');

    Route::resource('permissions', 'PermissionController');

    Route::resource('mp_mid_tid_user', 'MpMidTidUserController');

    Route::get('mp_user/ajaxListPhone', 'MpUserController@ajaxListUserWithPhone')->name('mp_users.ajaxListUserWithPhone');



    Route::get('/api/get_districts_from_province_code',
        'API\ContentController@get_districts_from_province_code'
    );
    Route::get('/api/get_wards_from_district_code_and_province_code',
        'API\ContentController@get_wards_from_district_code_and_province_code'
    );
    Route::get('/api/get_staff_from_department',
        'API\ContentController@get_staff_from_department'
    );
    Route::get('/api/get_audit_logs',
        'API\ContentController@get_audit_logs'
    );
    Route::get('/api/search_merchant_users',
        'API\ContentController@search_merchant_users'
    );
    Route::get('/api/get_latest_terminal_of_merchant',
        'API\ContentController@get_latest_terminal_of_merchant'
    );
    Route::get('/api/get_combine_info_mer_ter',
        'API\ContentController@get_combine_info_mer_ter'
    );
    Route::get('/api/clear_filter',
        'API\ContentController@clearFilter'
    );


    Route::resource('messages', 'MessageController');
    Route::resource('utils', 'UtilController');
    Route::post('utils/resetUsers', 'UtilController@resetUsers')->name('utils.resetUsers');
    Route::resource('banners', 'BannerController');
});

resources/views/layouts_mms/app.blade.php
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"/>
    <meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
    <meta charset="utf-8"/>
    <title>Merchant Portal Management</title>
    <meta name="description" content="overview &amp; stats"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0"/>
    <link rel="stylesheet" href="{{asset('css/bootstrap.min.css')}}"/>
    <link rel="stylesheet" href="{{asset('css/font-awesome.min.css')}}"/>
    @if (isset($new_select2) && $new_select2)
        <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.12/css/select2.min.css" rel="stylesheet" />
    @else
        <link rel="stylesheet" href="{{asset('css/select2.css')}}"/>
    @endif
    <link rel="stylesheet" href="{{asset('css/theme.css')}}?v=2"/>
    <link rel="stylesheet" href="{{asset('css/bootstrap-datetimepicker.css')}}">
    <link id="bsdp-css" href="{{asset('css/bootstrap-datepicker3.min.css')}}" rel="stylesheet">
    <link rel="stylesheet" href="{{asset('css/switch-button.css')}}"/>
    @if(isset($new_select2) && $new_select2)
        <style>
            .select2-search:after{
                content: none;
            }
        </style>
    @endif
    @yield('css')
</head>
<body class="no-skin">
<div id="navbar" class="navbar navbar-default">
    <div class="navbar-container" id="navbar-container">
        <button type="button" class="navbar-toggle menu-toggler pull-left" id="menu-toggler" style="z-index: 1">
            <span class="sr-only">menu</span><span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
        <div class="navbar-header pull-left">
            <div class="box clearfix">
                <div class="sidebar-toggle sidebar-collapse" id="sidebar-collapse">
                    <i class="default-icon fa fa-angle-double-left" data-icon1="default-icon fa fa-angle-double-left"
                       data-icon2="default-icon fa fa-angle-double-right"></i>
                </div>
                <a href="#" class="navbar-brand hidden-xs">
                    <img src="{{asset('images/logo.png')}}" width="182" height="41" alt="logo">
                </a>
            </div>
        </div>
        <div class="header-text hidden-xs">
            <p><span class="clred">Merchant</span><span class="clblue"> Portal</span> Management</p>
        </div>
        <div class="navbar-buttons navbar-header pull-right" role="navigation">
            <ul class="nav ace-nav">
                <li class="users">
                    <a data-toggle="dropdown" href="#" class="dropdown-toggle">
                        <img src="{{asset('images/ava.png')}}" width="40" height="40" alt="ava">
                        <span class="user-info">{{ Auth::user()->name }}</span>
                        <i class="default-icon fa fa-caret-down"></i>
                    </a>
                    <ul class="user-menu dropdown-menu-right dropdown-menu dropdown-caret dropdown-close">
                        <li><a href="{{ url('/users/' . Auth::user()->id . '/edit') }}"><i class="default-icon fa fa-user"></i>Chi tiết tài khoản</a></li>
                        <li class="divider"></li>
                        <li>
                            <a href="{{ url('/logout') }}"
                               onclick="event.preventDefault(); document.getElementById('logout-form').submit();">
                                <i class="default-icon fa fa-power-off"></i>Đăng xuất
                            </a>
                            <form id="logout-form" action="{{ url('/logout') }}" method="POST" style="display: none;">
                                @csrf
                            </form>
                        </li>
                    </ul>
                </li>
            </ul>
        </div>
    </div>
</div>

<div class="main-container" id="main-container">
    @include('layouts_mms.sidebar')
    <div class="main-content">
        {{ Breadcrumbs::render() }}
        <div class="page-content">
            <div class="page-content-area">
                @yield('content')
            </div>
        </div>
    </div>
    <a href="#" id="btn-scroll-up" class="btn-scroll-up btn btn-sm btn-inverse"> <i
                class="default-icon fa fa-angle-double-up icon-only bigger-110"></i> </a>
</div>

<script src="{{asset('js/ie8-responsive-file-warning.js')}}"></script>
<script src="{{asset('js/ie10-viewport-bug-workaround.js')}}"></script>
<script src="//code.jquery.com/jquery-3.3.1.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
<script src="//unpkg.com/bootstrap-datepicker@1.9.0/dist/js/bootstrap-datepicker.min.js"></script>
<script src="//unpkg.com/bootstrap-datepicker@1.9.0/dist/locales/bootstrap-datepicker.vi.min.js" charset="UTF-8"></script>
@if (isset($new_select2) && $new_select2)
<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.12/js/select2.full.min.js"></script>
@else
<script src="{{asset('js/select2.min.js')}}"></script>
@endif
<script src="{{asset('js/java.js')}}"></script>
<script src="{{asset('js/sms-extra.min.js')}}"></script>
<script src="{{asset('js/moment-with-locales.js')}}"></script>
<script>
    $(document).ready(function () {
        $('.select2').select2({'allowClear': true});
        $('.dp').datepicker({
            language: "vi"
        });
    })
</script>
@yield('scripts')

</body>

</html>

resources/views/layouts_mms/datatables_css.blade.php
<!-- DataTable Bootstrap -->
{{--<link href="https://cdn.datatables.net/1.10.20/css/dataTables.bootstrap4.min.css" rel="stylesheet">--}}
{{--<link rel="stylesheet" href="https://cdn.datatables.net/buttons/1.6.1/css/buttons.bootstrap4.min.css">--}}

resources/views/layouts_mms/datatables_js.blade.php
<!-- Datatables -->
<script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js" type="text/javascript"></script>
<script src="https://cdn.datatables.net/1.10.16/js/dataTables.bootstrap.min.js" type="text/javascript"></script>
<script src="https://cdn.datatables.net/responsive/2.2.1/js/dataTables.responsive.min.js"></script>
<script src="https://cdn.datatables.net/responsive/2.2.1/js/responsive.bootstrap.min.js"></script>
<script src="https://cdn.datatables.net/fixedheader/3.1.5/js/dataTables.fixedHeader.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/2.5.0/jszip.min.js" type="text/javascript"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.18/pdfmake.min.js" type="text/javascript"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.18/vfs_fonts.js" type="text/javascript"></script>
<script src="https://cdn.datatables.net/buttons/1.5.1/js/dataTables.buttons.min.js" type="text/javascript"></script>
<script src="https://cdn.datatables.net/buttons/1.5.1/js/buttons.bootstrap.min.js" type="text/javascript"></script>
<script src="https://cdn.datatables.net/buttons/1.5.1/js/buttons.html5.min.js" type="text/javascript"></script>
<script src="https://cdn.datatables.net/buttons/1.5.1/js/buttons.print.min.js" type="text/javascript"></script>
<script src="https://cdn.datatables.net/buttons/1.5.1/js/buttons.colVis.min.js" type="text/javascript"></script>
<script src="{{ asset('vendor/datatables/buttons.server-side.js') }}"></script>

resources/views/layouts_mms/daterange_picker_css.blade.php
<link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.css" />

resources/views/layouts_mms/daterange_picker_js.blade.php
<script type="text/javascript" src="https://cdn.jsdelivr.net/momentjs/latest/moment.min.js"></script>
<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.min.js"></script>
@if (isset($init_id))
    @foreach($init_id as $el_id)
        <script>
            {{ 'var ' . $el_id . "_startDate;"}}
            {{ 'var ' . $el_id . "_endDate;"}}
            var that = $('#{{$el_id}}');
            var autoUpdateInput = false;
            if("{{ session('filter_daterange_start') }}") {
                var startDate = new Date("{{ session('filter_daterange_start') }}");
                autoUpdateInput = true;
            }
            else {
                var startDate = new Date();
                startDate.setDate(startDate.getDate() - 3);
            }
            if("{{ session('filter_daterange_end') }}") {
                var endDate = new Date("{{ session('filter_daterange_end') }}");
                autoUpdateInput = true;
            }
            else {
                var endDate = new Date();
            }
            $(that).daterangepicker({
                    "autoUpdateInput": autoUpdateInput,
                    "startDate": startDate,
                    "endDate": endDate,
                    "locale": {
                        "format": "DD/MM/YYYY",
                        "separator": " - ",
                        "applyLabel": "Chọn",
                        "cancelLabel": "Hủy",
                        "fromLabel": "Từ",
                        "toLabel": "Đến",
                        "customRangeLabel": "Tùy chọn",
                        "daysOfWeek": [
                            "CN",
                            "T2",
                            "T3",
                            "T4",
                            "T5",
                            "T6",
                            "T7"
                        ],
                        "monthNames": [
                            "Tháng 1",
                            "Tháng 2",
                            "Tháng 3",
                            "Tháng 4",
                            "Tháng 5",
                            "Tháng 6",
                            "Tháng 7",
                            "Tháng 8",
                            "Tháng 9",
                            "Tháng 10",
                            "Tháng 11",
                            "Tháng 12",
                        ],
                        "firstDay": 1
                    }
                }, (from_date, to_date) => {
                        {{$el_id . "_startDate"}} = from_date.format('YYYY-MM-DD');
                        {{$el_id . "_endDate"}} = to_date.format('YYYY-MM-DD');
                    $(that).val(from_date.format('DD/MM/YYYY') + ' - ' + to_date.format('DD/MM/YYYY'));
                    if (window.LaravelDataTables && window.LaravelDataTables['dataTableBuilder']) {
                        window.LaravelDataTables['dataTableBuilder'].draw();
                    }
                }
            );
        </script>
    @endforeach
@endif

resources/views/layouts_mms/menu.blade.php
<li>
    <a href="#"><i class="menu-icon fa fa-dashboard"></i><span class="menu-text"> Bảng điều khiển</span></a>
</li>
<li class="{{ Request::is('trials*') ? 'active' : '' }}">
    <a href="{{ route('trials.index') }}"><i class="menu-icon fa fa-users"></i><span class="menu-text">Tài khoản thử nghiệm</span></a>
</li>
<li class="{{ Request::is('stores*') ? 'active' : '' }}">
    <a href="#" class="dropdown-toggle"><i class="menu-icon fa fa-list-alt"></i><span class="menu-text">Quản lý Merchant</span><b
            class="arrow fa fa-angle-down"></b></a><b class="arrow"></b>
    <ul class="submenu">
        <li class="hsub {{ \Route::current()->getName() == 'stores.index' ? 'active' : '' }}">
            <a href="{{ route('stores.index') }}"><i class="menu-icon fa"></i><span class="menu-text">Danh sách Merchant</span></a>
            <b class="arrow"></b>
        </li>
        <li class="hsub {{ \Route::current()->getName() == 'stores.activeList' ? 'active' : '' }}">
            <a href="{{ route('stores.activeList') }}"><i class="menu-icon fa"></i><span class="menu-text">Danh sách đã duyệt</span></a>
            <b class="arrow"></b>
        </li>
        <li class="hsub {{ \Route::current()->getName() == 'stores.registerList' ? 'active' : '' }}">
            <a href="{{ route('stores.registerList') }}"><i class="menu-icon fa"></i><span class="menu-text">Danh sách gửi đăng ký</span></a>
            <b class="arrow"></b>
        </li>
        <li class="hsub {{\Route::current()->getName() == 'stores.needApproveList' ? 'active' : '' }}">
            <a href="{{ route('stores.needApproveList') }}"><i class="menu-icon fa"></i><span class="menu-text">Danh sách chờ duyệt</span></a>
            <b class="arrow"></b>
        </li>
        <li class="hsub {{ \Route::current()->getName() == 'stores.deniedList' ? 'active' : '' }}">
            <a href="{{ route('stores.deniedList') }}"><i class="menu-icon fa"></i><span class="menu-text">Danh sách bị từ chối</span></a>
            <b class="arrow"></b>
        </li>
        <li class="hsub {{ \Route::current()->getName() == 'stores.lockedList' ? 'active' : '' }}">
            <a href="{{ route('stores.lockedList') }}"><i class="menu-icon fa"></i><span class="menu-text">Danh sách đóng</span></a>
            <b class="arrow"></b>
        </li>
    </ul>
</li>
<li class="{{ Request::is('terminals*') || Request::is('terminalBatches*') ? 'active' : '' }}">
    <a href="#" class="dropdown-toggle"><i class="menu-icon fa fa-terminal"></i><span class="menu-text">Quản lý Terminal</span><b
            class="arrow fa fa-angle-down"></b></a><b class="arrow"></b>
    <ul class="submenu">
        <li class="hsub {{ \Route::current()->getName() == 'terminals.index' ? 'active' : '' }}">
            <a href="{{ route('terminals.index') }}"><i class="menu-icon fa"></i><span class="menu-text">Danh sách Terminal</span></a>
            <b class="arrow"></b>
        </li>
        <li class="hsub {{\Route::current()->getName() == 'terminals.needApproveList' ? 'active' : '' }}">
            <a href="{{ route('terminals.needApproveList') }}"><i class="menu-icon fa"></i><span class="menu-text">Danh sách chờ duyệt</span></a>
            <b class="arrow"></b>
        </li>
        <li class="hsub {{ \Route::current()->getName() == 'terminals.approvedList' ? 'active' : '' }}">
            <a href="{{ route('terminals.approvedList') }}"><i class="menu-icon fa"></i><span class="menu-text">Danh sách đã duyệt</span></a>
            <b class="arrow"></b>
        </li>
        <li class="hsub {{ \Route::current()->getName() == 'terminals.deniedList' ? 'active' : '' }}">
            <a href="{{ route('terminals.deniedList') }}"><i class="menu-icon fa"></i><span class="menu-text">Danh sách bị từ chối</span></a>
            <b class="arrow"></b>
        </li>
        <li class="hsub {{ \Route::current()->getName() == 'terminals.lockedList' ? 'active' : '' }}">
            <a href="{{ route('terminals.lockedList') }}"><i class="menu-icon fa"></i><span class="menu-text">Danh sách đóng</span></a>
            <b class="arrow"></b>
        </li>
        <li class="hsub {{ Request::is('terminalBatches*') ? 'active' : '' }}">
            <a href="{{ route('terminalBatches.index') }}"><i class="menu-icon fa"></i><span class="menu-text">Danh sách theo lô</span></a>
            <b class="arrow"></b>
        </li>
    </ul>
</li>
<li class="{{ Request::is('enjoyments*') ? 'active' : '' }}">
    <a href="#" class="dropdown-toggle"><i class="menu-icon fa fa-credit-card"></i><span class="menu-text">Quản lý thụ hưởng</span><b
            class="arrow fa fa-angle-down"></b></a><b class="arrow"></b>
    <ul class="submenu">
        <li class="hsub {{ \Route::current()->getName() == 'enjoyments.changeEnjoyment' ||
            \Route::current()->getName() == 'enjoyments.chooseMerchant' ? 'active' : '' }}">
            <a href="{{ route('enjoyments.changeEnjoyment') }}"><i class="menu-icon fa"></i><span class="menu-text">Tạo thay đổi thụ hưởng</span></a>
            <b class="arrow"></b>
        </li>
        <li class="hsub {{ \Route::current()->getName() == 'enjoyments.index' ||
            \Route::current()->getName() == 'enjoyments.index' ? 'active' : '' }}">
            <a href="{{ route('enjoyments.index') }}"><i class="menu-icon fa"></i><span class="menu-text">Danh sách đổi thụ hưởng</span></a>
            <b class="arrow"></b>
        </li>
    </ul>
</li>
@if(Auth::user()->hasrole('Mở khóa Merchant User(s)') || Auth::user()->email === 'devmp@gmail.com')
    <li class="{{ Request::is('utils*') ? 'active' : '' }}">
        <a href="{{ route('utils.index') }}"><i class="menu-icon fa fa-database"></i><span class="menu-text">Mở khóa Merchant User</span></a>
    </li>
@endif
@if(Auth::user()->email === 'devmp@gmail.com' || Auth::user()->hasPermissionTo('Notification'))
<li class="{{ Request::is('messages*') ? 'active' : '' }}">
    <a href="{{ route('messages.index') }}"><i class="menu-icon fa fa-bell"></i><span class="menu-text">Quản lý thông báo</span></a>
</li>
@endif
@if(Auth::user()->email === 'devmp@gmail.com' || Auth::user()->hasPermissionTo('Banner'))
<li class="{{ Request::is('banners*') ? 'active' : '' }}">
    <a href="{{ route('banners.index') }}"><i class="menu-icon fa fa-flag"></i><span class="menu-text">Quản lý banner</span></a>
</li>
@endif

@if(Auth::user()->email === 'devmp@gmail.com' || Auth::user()->hasrole('Super admin'))
    <li class="{{ Request::is('smsLogs*') ? 'active' : '' }}">
        <a href="{{ route('smsLogs.index') }}"><i class="menu-icon fa fa-comment"></i><span
                class="menu-text">SMS Logging</span></a>
    </li>
    <li class="{{ (Request::is('users*') ||Request::is('roles*') || Request::is('permissions*'))  ? 'active' : '' }}">
        <a href="#" class="dropdown-toggle"><i class="menu-icon fa fa-cogs"></i><span class="menu-text">Thiết lập</span><b
                    class="arrow fa fa-angle-down"></b></a><b class="arrow"></b>
        <ul class="submenu">
                <li class="hsub {{ Request::is('users*') ? 'active' : '' }}">
                    <a href="{{ route('users.index') }}"><i class="menu-icon fa fa-caret-right"></i>Tài khoản</a>
                    <b class="arrow"></b>
                </li>
            <li class="hsub {{ Request::is('roles*') ? 'active' : '' }}">
                <a href="{{ route('roles.index') }}"><i class="menu-icon fa fa-caret-right"></i>Vai trò</a>
                <b class="arrow"></b>
            </li>
            <li class="hsub {{ Request::is('permissions*') ? 'active' : '' }}">
                <a href="{{ route('permissions.index') }}"><i class="menu-icon fa fa-caret-right"></i>Các quyền</a>
                <b class="arrow"></b>
            </li>
            {{--<li class="hsub">--}}
                {{--<a href="#"><i class="menu-icon fa fa-caret-right"></i>Đồng bộ từ MMS DB</a>--}}
                {{--<b class="arrow"></b>--}}
            {{--</li>--}}
        </ul>
    </li>
@endif

resources/views/layouts_mms/page_header.blade.php
<div class="page-header">
    <h1 class="page-header-left">{{$header}}</h1>
    @if (isset($buttons))
        @if ($buttons)
            @foreach( $buttons as $button )
                <div class="page-header-right">
                    <a class="btn btn-primary" href="{{$button['link']}}">
                        <i class="{{$button['icon']}}"></i>{{$button['title']}}
                    </a>
                </div>
            @endforeach
        @endif
    @endif
    <div class="clearfix"></div>
</div>

resources/views/layouts_mms/sidebar.blade.php
<div id="sidebar" class="sidebar responsive">
    <ul class="nav nav-list">
       @include('layouts_mms.menu')
    </ul>
</div>