routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('/home');
});


Auth::routes();
Route::group(['middleware' => 'auth'], function () {

    Route::get('/home', 'HomeController@index')->name('home');

    Route::get('stores/{id}/sale_accept', 'StoreController@saleAccept')->name('stores.sale_accept');
    Route::get('stores/{id}/control_accept', 'StoreController@controlAccept')->name('stores.control_accept');
    Route::get('stores/{id}/notify_mms', 'StoreController@notifyMMS')->name('stores.notify_mms');
    Route::get('stores/{id}/retry_mms', 'StoreController@retryMMS')->name('stores.retry_mms');
    Route::get('stores/{id}/reject', 'StoreController@reject')->name('stores.reject');
    Route::get('stores/{id}/reopen_upload_document', 'StoreController@reopenUploadDocument')->name('stores.reopen');
    Route::post('stores/updateStore/{id}', 'StoreController@updateStore')->name('stores.updateStore');
    Route::post('stores/updateContract/{id}', 'StoreController@updateContract')->name('stores.updateContract');
    Route::post('stores/reUploadContract/{id}', 'StoreController@reUploadContract')->name('stores.reUploadContract');
    Route::post('stores/saleAction/{id}', 'StoreController@saleAction')->name('stores.saleAction');
    Route::post('stores/controlAction/{id}', 'StoreController@controlAction')->name('stores.controlAction');
    Route::post('stores/sendRequest/{id}', 'StoreController@sendRequest')->name('stores.sendRequest');
    Route::post('stores/lockMerchant', 'StoreController@lockMerchant')->name('stores.lockMerchant');
    Route::post('stores/unlockMerchant', 'StoreController@unlockMerchant')->name('stores.unlockMerchant');

    Route::get('stores/needApproveList', 'StoreController@needApproveList')->name('stores.needApproveList');
    Route::get('stores/activeList', 'StoreController@activeList')->name('stores.activeList');
    Route::get('stores/registerList', 'StoreController@registerList')->name('stores.registerList');
    Route::get('stores/approvedList', 'StoreController@approvedList')->name('stores.approvedList');
    Route::get('stores/deniedList', 'StoreController@deniedList')->name('stores.deniedList');
    Route::get('stores/lockedList', 'StoreController@lockedList')->name('stores.lockedList');
    Route::resource('stores', 'StoreController')->middleware('auth');

    Route::resource('trials', 'TrialController');


    Route::post('terminals/{id}/reject', 'TerminalController@reject')->name('terminals.reject');
    Route::get('terminals/{id}/approve', 'TerminalController@approve')->name('terminals.approve');
    Route::get('terminals/{id}/sendRequest', 'TerminalController@sendRequest')->name('terminals.sendRequest');
    Route::get('terminals/{id}/showFirstTerminal', 'TerminalController@showFirstTerminal')->name('terminals.showFirstTerminal');
    Route::get('terminals/{id}/editFirstTerminal', 'TerminalController@editFirstTerminal')->name('terminals.editFirstTerminal');
    Route::patch('terminals/updateFirstTerminal/{id}', 'TerminalController@updateFirstTerminal')->name('terminals.updateFirstTerminal');
    Route::get('terminals/needApproveList', 'TerminalController@needApproveList')->name('terminals.needApproveList');
    Route::get('terminals/approvedList', 'TerminalController@approvedList')->name('terminals.approvedList');
    Route::get('terminals/deniedList', 'TerminalController@deniedList')->name('terminals.deniedList');
    Route::get('terminals/lockedList', 'TerminalController@lockedList')->name('terminals.lockedList');
    Route::get('terminals/ajaxListMerchant', 'TerminalController@ajaxListMerchant')->name('terminals.ajaxListMerchant');
    Route::get('terminals/ajaxListMerchantWithAll', 'TerminalController@ajaxListMerchantWithAll')->name('terminals.ajaxListMerchantWithAll');
    Route::get('terminals/ajaxListTerminalByMerchantCode', 'TerminalController@ajaxListTerminalByMerchantCode')->name('terminals.ajaxListTerminalByMerchantCode');

    Route::get('terminals/ajaxFindBankAccount', 'TerminalController@ajaxFindBankAccount')->name('terminals.ajaxFindBankAccount');
    Route::post('stores/lockTerminal', 'TerminalController@lockTerminal')->name('terminals.lockTerminal');
    Route::post('stores/unlockTerminal', 'TerminalController@unlockTerminal')->name('terminals.unlockTerminal');

    Route::resource('terminals', 'TerminalController')->middleware('auth');

    Route::resource('terminalBatches', 'MpTerminalBatchController')->middleware('auth');
    Route::post('terminalBatches/{id}/reject', 'MpTerminalBatchController@reject')->name('terminalBatches.reject');
    Route::get('terminalBatches/{id}/approve', 'MpTerminalBatchController@approve')->name('terminalBatches.approve');
    Route::get('terminalBatches/{id}/reopenForEditTerminals', 'MpTerminalBatchController@reopenForEditTerminals')
        ->name('terminalBatches.reopenForEditTerminals');

    // enjoyments
    Route::get('enjoyments/changeEnjoyment', 'EnjoymentsController@changeEnjoyment')->name('enjoyments.changeEnjoyment');
    Route::get('enjoyments/index', 'EnjoymentsController@index')->name('enjoyments.index');
    Route::get('enjoyments/chooseMerchant', 'EnjoymentsController@chooseMerchant')->name('enjoyments.chooseMerchant');
    Route::post('enjoyments/chooseMerchant', 'EnjoymentsController@chooseMerchant')->name('enjoyments.chooseMerchant');
    Route::post('enjoyments/upsertEnjoyment', 'EnjoymentsController@upsertEnjoyment')->name('enjoyments.upsertEnjoyment');
    Route::get('enjoyments/ajaxFindBankAccount', 'EnjoymentsController@ajaxFindBankAccount')->name('enjoyments.ajaxFindBankAccount');
    Route::resource('enjoyments', 'EnjoymentsController')->middleware('auth');

    Route::resource('smsLogs', 'SmsLogController')->middleware('auth');

    Route::resource('users', 'UserController');

    Route::resource('roles', 'RoleController');

    Route::resource('permissions', 'PermissionController');

    Route::resource('mp_mid_tid_user', 'MpMidTidUserController');

    Route::get('mp_user/ajaxListPhone', 'MpUserController@ajaxListUserWithPhone')->name('mp_users.ajaxListUserWithPhone');



    Route::get('/api/get_districts_from_province_code',
        'API\ContentController@get_districts_from_province_code'
    );
    Route::get('/api/get_wards_from_district_code_and_province_code',
        'API\ContentController@get_wards_from_district_code_and_province_code'
    );
    Route::get('/api/get_staff_from_department',
        'API\ContentController@get_staff_from_department'
    );
    Route::get('/api/get_audit_logs',
        'API\ContentController@get_audit_logs'
    );
    Route::get('/api/search_merchant_users',
        'API\ContentController@search_merchant_users'
    );
    Route::get('/api/get_latest_terminal_of_merchant',
        'API\ContentController@get_latest_terminal_of_merchant'
    );
    Route::get('/api/get_combine_info_mer_ter',
        'API\ContentController@get_combine_info_mer_ter'
    );
    Route::get('/api/clear_filter',
        'API\ContentController@clearFilter'
    );


    Route::resource('messages', 'MessageController');
    Route::resource('utils', 'UtilController');
    Route::post('utils/resetUsers', 'UtilController@resetUsers')->name('utils.resetUsers');
    Route::resource('banners', 'BannerController');
});

app/Http/Controllers/MpTerminalBatchController.php
<?php

namespace App\Http\Controllers;

use App\Bank;
use App\DataTables\ListTerminalsInBatchDataTable;
use App\DataTables\MpTerminalBatchDataTable;
use App\Http\Requests;
use App\Http\Requests\CreateMpTerminalBatchRequest;
use App\Http\Requests\UpdateMpTerminalBatchRequest;
use App\Libraries\BaseFunction;
use App\MpTerminal;
use App\MpTerminalBatch;
use App\Repositories\MpTerminalBatchRepository;
use App\Store;
use App\TerminalHistory;
use Flash;
use App\Http\Controllers\AppBaseController;
use Ramsey\Uuid\Uuid;
use Response;
use Symfony\Component\Console\Terminal;
use Symfony\Component\HttpFoundation\Request;

class MpTerminalBatchController extends AppBaseController
{
    /** @var  MpTerminalBatchRepository */
    private $mpTerminalBatchRepository;

    public function __construct(MpTerminalBatchRepository $mpTerminalBatchRepo)
    {
        $this->mpTerminalBatchRepository = $mpTerminalBatchRepo;
    }

    /**
     * Display a listing of the MpTerminalBatch.
     *
     * @param MpTerminalBatchDataTable $mpTerminalBatchDataTable
     * @return Response
     */
    public function index(MpTerminalBatchDataTable $mpTerminalBatchDataTable)
    {
        $filterable_status = array_keys(MpTerminalBatch::STATUS);

        return $mpTerminalBatchDataTable->render('mp_terminal_batches.index', compact('filterable_status'));
    }

    /**
     * Show the form for creating a new MpTerminalBatch.
     *
     * @return Response
     */
    public function create()
    {
        $banks = Bank::all();
        return view('mp_terminal_batches.create', compact(
            'banks'
        ));
    }

    /**
     * Store a newly created MpTerminalBatch in storage.
     *
     * @param CreateMpTerminalBatchRequest $request
     *
     * @return Response
     */
    public function store(CreateMpTerminalBatchRequest $request)
    {
        $input = $request->all();

        $folder_path = public_path('api_uploads/terminal_batch/' . $input['merchant_code']);

        if ($request->hasFile('file_contract')) {
            $file_contract = $request->file('file_contract');
            $new_name = Uuid::uuid4() . '.' . $file_contract->getClientOriginalExtension();
            $file_contract->move($folder_path, $new_name);
            $input['file_contract'] = $new_name;
        }

        if ($request->hasFile('file_authorize')) {
            $file_authorize = $request->file('file_authorize');
            $new_name = Uuid::uuid4() . '.' . $file_authorize->getClientOriginalExtension();
            $file_authorize->move($folder_path, $new_name);
            $input['file_authorize'] = $new_name;
        }

        if ($request->hasFile('file_terminals')) {
            $file_terminals = $request->file('file_terminals');
            $new_name = Uuid::uuid4() . '.' . $file_terminals->getClientOriginalExtension();
            $file_terminals->move($folder_path, $new_name);
            $input['file_terminals'] = $new_name;
        }

        $input['created_by'] = \Auth::user()->id;
        $input['updated_by'] = \Auth::user()->id;
        $input['status'] = MpTerminalBatch::STATUS_INIT;

        $mpTerminalBatch = $this->mpTerminalBatchRepository->create($input);

        Flash::success('Mp Terminal Batch saved successfully.');

        return redirect(route('terminalBatches.index'));
    }

    /**
     * Display the specified MpTerminalBatch.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $batch = $this->mpTerminalBatchRepository->find($id);

        if (empty($batch)) {
            Flash::error('Mp Terminal Batch not found');

            return redirect(route('terminalBatches.index'));
        }

        $listTerminalsInBatchDataTable = new ListTerminalsInBatchDataTable($batch);

        return $listTerminalsInBatchDataTable->render('mp_terminal_batches.show', compact('batch'));
    }

    /**
     * Show the form for editing the specified MpTerminalBatch.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $mpTerminalBatch = $this->mpTerminalBatchRepository->find($id);

        if (empty($mpTerminalBatch)) {
            Flash::error('Mp Terminal Batch not found');

            return redirect(route('terminalBatches.index'));
        }

        return view('mp_terminal_batches.edit')->with('mpTerminalBatch', $mpTerminalBatch);
    }

    /**
     * Update the specified MpTerminalBatch in storage.
     *
     * @param  int              $id
     * @param UpdateMpTerminalBatchRequest $request
     *
     * @return Response
     */
    public function update($id, UpdateMpTerminalBatchRequest $request)
    {
        $mpTerminalBatch = $this->mpTerminalBatchRepository->find($id);

        if (empty($mpTerminalBatch)) {
            Flash::error('Mp Terminal Batch not found');

            return redirect(route('terminalBatches.index'));
        }

        $mpTerminalBatch = $this->mpTerminalBatchRepository->update($request->all(), $id);

        Flash::success('Mp Terminal Batch updated successfully.');

        return redirect(route('terminalBatches.index'));
    }

    /**
     * Remove the specified MpTerminalBatch from storage.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function destroy($id)
    {
        $mpTerminalBatch = $this->mpTerminalBatchRepository->find($id);

        if (empty($mpTerminalBatch)) {
            Flash::error('Mp Terminal Batch not found');

            return redirect(route('terminalBatches.index'));
        }

        $this->mpTerminalBatchRepository->delete($id);

        Flash::success('Mp Terminal Batch deleted successfully.');

        return redirect(route('terminalBatches.index'));
    }

    public function reject($id, Request $request){
        $batch = $this->mpTerminalBatchRepository->find($id);

        if (empty($batch)) {
            Flash::error('Không tìm thấy lô terminal này');

            return redirect(route('terminalBatches.index'));
        }

        $user = auth()->user();
        $rejectReason = $request->get('reject_reason') ?? null;
        if ($rejectReason === '0') {
            $rejectReason = $request->get('reason');
        }
        if ($batch->status == $this->mpTerminalBatchRepository->model()::STATUS_WAIT_SALE_APPROVE) {
            if ($user->hasrole('Kinh doanh')) {
                if ($request->has('reject_reason')) {
                    $this->mpTerminalBatchRepository->update([
                        'status' => $this->mpTerminalBatchRepository->model()::STATUS_SALE_DENIED,
                        'reject_reason' => $rejectReason
                    ], $id);
                    $this->saveLogHandleToDb($batch['id'], TerminalHistory::TYPE_BATCH_SALE_DENIED, $request->get('reason'));
                    Flash::info('Kinh doanh từ chối');
                }
            } else {
                Flash::error('You have no permission to reject.');
            }
        } else if ($batch->status == $this->mpTerminalBatchRepository->model()::STATUS_WAIT_CONTROL_APPROVE) {
            if ($user->hasrole('Đối soát')) {
                if ($request->has('reject_reason')) {
                $this->mpTerminalBatchRepository->update([
                    'status' => $this->mpTerminalBatchRepository->model()::STATUS_CONTROL_DENIED,
                    'reject_reason' => $rejectReason
                ], $id);
                    $this->saveLogHandleToDb($batch['id'], TerminalHistory::TYPE_BATCH_REVIEW_DENIED, $request->get('reason'));
                Flash::info('Đối soát từ chối');
            }
            } else {
                Flash::error('You have no permission to reject.');
            }
        } else {
            Flash::error('Terminal batch status not available');
        }
        return redirect(route('terminalBatches.show', ['id' => $id]));
    }

    public function approve($id, Request $request){
        $batch = $this->mpTerminalBatchRepository->find($id);
        if (empty($batch)) {
            Flash::error('Không tìm thấy lô terminal này');

            return redirect(route('terminalBatches.index'));
        }
        $user = auth()->user();
        if ($batch->status == $this->mpTerminalBatchRepository->model()::STATUS_WAIT_SALE_APPROVE) {
            if ($user->hasrole('Kinh doanh')) {
                $this->mpTerminalBatchRepository->update(['status' => $this->mpTerminalBatchRepository->model()::STATUS_WAIT_CONTROL_APPROVE], $id);
                $this->saveLogHandleToDb($batch['id'], TerminalHistory::TYPE_BATCH_SALE_APPROVED, $request->get('reason'));
                Flash::success('Duyệt lô terminal thành công!');
            } else {
                Flash::error('You have no permission to reject.');
            }
        } else if ($batch->status == $this->mpTerminalBatchRepository->model()::STATUS_WAIT_CONTROL_APPROVE) {
            if ($user->hasrole('Đối soát')) {
                $merchant = Store::where('merchant_code', $batch->merchant_code)->first();
                if (!$merchant) {
                    Flash::error('Không tồn tại merchant tương ứng với merchant code.' . $batch->merchant_code);
                }
                elseif ($merchant->status === BaseFunction::STATUS_LOCK) {
                    Flash::error(sprintf('Hiện tại merchant %s đang ở trạng thái đóng. Vui lòng kiểm tra lại!', $batch->merchant_code));
                }
                else {
                    $this->mpTerminalBatchRepository->update(['status' => $this->mpTerminalBatchRepository->model()::STATUS_CONTROL_APPROVED], $id);
                    $this->saveLogHandleToDb($batch['id'], TerminalHistory::TYPE_BATCH_REVIEW_APPROVED, $request->get('reason'));
                    Flash::success('Duyệt lô terminal thành công!');
                }
            } else {
                Flash::error('You have no permission to reject.');
            }
        } else {

resources/views/mp_terminal_batches/create.blade.php
@extends('layouts_mms.app', ['new_select2' => true])

@section('content')
    @include('flash::message')

    <div class="container-fluid">
        <div class="animated fadeIn">
            {{--            @include('coreui-templates::common.errors')--}}
            @include('layouts_mms.page_header', ['header' => 'Thêm mới Terminal theo lô'])
            {!! Form::open(['route' => 'terminalBatches.store','files' =>true,'enctype'=>'multipart/form-data']) !!}

            @include('mp_terminal_batches.fields')

            {!! Form::close() !!}
        </div>
    </div>
@endsection

resources/views/mp_terminal_batches/datatables_actions.blade.php
<div class="hidden-sm hidden-xs action-buttons">
    <a class="blue" href="{{ route('terminalBatches.show', $id) }}">
        <i class="ace-icon fa fa-search-plus bigger-130"></i>
    </a>
</div>

resources/views/mp_terminal_batches/edit.blade.php
@extends('layouts.app')

@section('content')
    <ol class="breadcrumb">
          <li class="breadcrumb-item">
             <a href="{!! route('terminalBatches.index') !!}">Mp Terminal Batch</a>
          </li>
          <li class="breadcrumb-item active">Edit</li>
        </ol>
    <div class="container-fluid">
         <div class="animated fadeIn">
             @include('coreui-templates::common.errors')
             <div class="row">
                 <div class="col-lg-12">
                      <div class="card">
                          <div class="card-header">
                              <i class="fa fa-edit fa-lg"></i>
                              <strong>Edit Mp Terminal Batch</strong>
                          </div>
                          <div class="card-body">
                              {!! Form::model($mpTerminalBatch, ['route' => ['terminalBatchesupdate', $mpTerminalBatch->id], 'method' => 'patch']) !!}

                              @include('mp_terminal_batches.fields')

                              {!! Form::close() !!}
                            </div>
                        </div>
                    </div>
                </div>
         </div>
    </div>
@endsection

resources/views/mp_terminal_batches/index.blade.php
@extends('layouts_mms.app', ['new_select2' => false])

@section('content')
    @if(Auth::user()->hasrole('Sale admin'))
        @include('layouts_mms.page_header', ['header' => 'Tổng hợp danh sách Terminal theo lô', 'buttons' => [['title' => 'Thêm mới', 'link' => route('terminalBatches.create'), 'icon' => 'fa fa-plus-circle']]])
    @else
        @include('layouts_mms.page_header', ['header' => 'Tổng hợp danh sách Terminal theo lô'])
    @endif
    @include('flash::message')
    <div class="row dataTables_filter ">
        <div class="col-sm-3 form-group">
            <label>Tìm kiếm:</label>
            <input id="filter_query" class="form-control" placeholder="-- Nhập từ khóa tìm kiếm --" value="{{ session()->get('terminal_batch_filter_query') }}">
        </div>
        <div class="col-sm-3 form-group">
            <label>Thời gian:</label>
            <input class="form-control drp" id="date_range_search" placeholder="-- Chọn ngày tìm kiếm --">
        </div>
        @if (count($filterable_status) > 0)
            <div class="col-sm-3 form-group">
                <label>Trạng thái:</label>
                <select id="filter_status" name="filter_status" class="form-control select2"
                        data-placeholder="-- Chọn trạng thái --">
                    <option></option>
                    @foreach($filterable_status as $filterStatus)
                        <option value="{{ $filterStatus }}"
                            {{ session()->get('terminal_filter_status') && session()->get('terminal_batch_filter_status') == $filterStatus ? 'selected' : '' }}
                        >
                            {{ \App\MpTerminalBatch::STATUS[$filterStatus] }}
                        </option>
                    @endforeach
                </select>
            </div>
        @endif
    </div>
    <div class="row">
        <div class="col-xs-12">
            @include('mp_terminal_batches.table')
        </div>
    </div>
@endsection

resources/views/mp_terminal_batches/list_terminals_table.blade.php
@section('css')
    @include('layouts_mms.datatables_css')
    @include('layouts_mms.daterange_picker_css')
@endsection

{!! $dataTable->table(['width' => '100%', 'class' => 'table table-striped table-bordered']) !!}

resources/views/mp_terminal_batches/show.blade.php
@extends('layouts_mms.app')

@section('content')
    @include('flash::message')

    <div class="container-fluid">
        <div class="animated fadeIn">
            @include('coreui-templates::common.errors')
            @include('layouts_mms.page_header', ['header' => 'Chi tiết Terminal theo lô'])
            @include('mp_terminal_batches.show_fields')
        </div>
    </div>
@endsection

@section('scripts')
    @include('layouts_mms.datatables_js')
    {!! $dataTable->scripts() !!}

    <script type="text/javascript">
        $("input[name='reject_reason']").on('change', function () {
            $('.error-reject-reason').html('')
        });

        $('#reject-terminal-batch').on('click', function () {
            var reject_type = $("input[name='reject_reason']:checked").val();
            if (reject_type) {
                if (reject_type == 0 && $("textarea[name='reason']").val().length == 0) {
                    $('.error-reject-reason').html('Vui lòng nhập lý do từ chối duyệt Terminal')
                }
                else {
                    $('.error-reject-reason').html('');
                    $("#rejectTerminalForm").submit()
                }
            }
            else {
                $('.error-reject-reason').html('Vui lòng chọn 1 lý do')
            }
        })
    </script>
@endsection

resources/views/mp_terminal_batches/table.blade.php
@section('css')
    @include('layouts_mms.datatables_css')
    @include('layouts_mms.daterange_picker_css')
@endsection

{!! $dataTable->table(['width' => '100%', 'class' => 'table table-striped table-bordered']) !!}

@section('scripts')
    @include('layouts_mms.daterange_picker_js', ['init_id' => ['date_range_search']])
    @include('layouts_mms.datatables_js')
    {!! $dataTable->scripts() !!}
    <script>
        var queryTypingTimer;
        var doneTypingInterval = 1000;
        var $input = $('#filter_query');
        $input.on('keyup', function () {
            clearTimeout(queryTypingTimer);
            queryTypingTimer = setTimeout(doneFilterTyping, doneTypingInterval);
        });
        $input.on('keydown', function () {
            clearTimeout(queryTypingTimer);
        });
        function doneFilterTyping () {
            if (window.LaravelDataTables && window.LaravelDataTables['dataTableBuilder']){
                window.LaravelDataTables['dataTableBuilder'].search($input.val()).draw();
            }
        }
        $('#filter_status').on('change', function () {
            if (window.LaravelDataTables && window.LaravelDataTables['dataTableBuilder']){
                window.LaravelDataTables['dataTableBuilder'].draw();
            }
        });
        $('#merchant_code').on('change', function () {
            if (window.LaravelDataTables && window.LaravelDataTables['dataTableBuilder']){
                window.LaravelDataTables['dataTableBuilder'].draw();
            }
        });
        $(document).ready(function () {
            $('.select2-ajax').select2({
                placeholder: "-- Chọn merchant --",
                minimumInputLength: 2,
                ajax: {
                    url: '/terminals/ajaxListMerchant',
                    dataType: 'json',
                    data: function (params) {
                        return {
                            q: $.trim(params.term)
                        };
                    },
                    processResults: function (data) {
                        return {
                            results: data
                        };
                    },
                    cache: true
                }
            });
        });
    </script>
@endsection