routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('/home');
});


Auth::routes();
Route::group(['middleware' => 'auth'], function () {

    Route::get('/home', 'HomeController@index')->name('home');

    Route::get('stores/{id}/sale_accept', 'StoreController@saleAccept')->name('stores.sale_accept');
    Route::get('stores/{id}/control_accept', 'StoreController@controlAccept')->name('stores.control_accept');
    Route::get('stores/{id}/notify_mms', 'StoreController@notifyMMS')->name('stores.notify_mms');
    Route::get('stores/{id}/retry_mms', 'StoreController@retryMMS')->name('stores.retry_mms');
    Route::get('stores/{id}/reject', 'StoreController@reject')->name('stores.reject');
    Route::get('stores/{id}/reopen_upload_document', 'StoreController@reopenUploadDocument')->name('stores.reopen');
    Route::post('stores/updateStore/{id}', 'StoreController@updateStore')->name('stores.updateStore');
    Route::post('stores/updateContract/{id}', 'StoreController@updateContract')->name('stores.updateContract');
    Route::post('stores/reUploadContract/{id}', 'StoreController@reUploadContract')->name('stores.reUploadContract');
    Route::post('stores/saleAction/{id}', 'StoreController@saleAction')->name('stores.saleAction');
    Route::post('stores/controlAction/{id}', 'StoreController@controlAction')->name('stores.controlAction');
    Route::post('stores/sendRequest/{id}', 'StoreController@sendRequest')->name('stores.sendRequest');
    Route::post('stores/lockMerchant', 'StoreController@lockMerchant')->name('stores.lockMerchant');
    Route::post('stores/unlockMerchant', 'StoreController@unlockMerchant')->name('stores.unlockMerchant');

    Route::get('stores/needApproveList', 'StoreController@needApproveList')->name('stores.needApproveList');
    Route::get('stores/activeList', 'StoreController@activeList')->name('stores.activeList');
    Route::get('stores/registerList', 'StoreController@registerList')->name('stores.registerList');
    Route::get('stores/approvedList', 'StoreController@approvedList')->name('stores.approvedList');
    Route::get('stores/deniedList', 'StoreController@deniedList')->name('stores.deniedList');
    Route::get('stores/lockedList', 'StoreController@lockedList')->name('stores.lockedList');
    Route::resource('stores', 'StoreController')->middleware('auth');

    Route::resource('trials', 'TrialController');


    Route::post('terminals/{id}/reject', 'TerminalController@reject')->name('terminals.reject');
    Route::get('terminals/{id}/approve', 'TerminalController@approve')->name('terminals.approve');
    Route::get('terminals/{id}/sendRequest', 'TerminalController@sendRequest')->name('terminals.sendRequest');
    Route::get('terminals/{id}/showFirstTerminal', 'TerminalController@showFirstTerminal')->name('terminals.showFirstTerminal');
    Route::get('terminals/{id}/editFirstTerminal', 'TerminalController@editFirstTerminal')->name('terminals.editFirstTerminal');
    Route::patch('terminals/updateFirstTerminal/{id}', 'TerminalController@updateFirstTerminal')->name('terminals.updateFirstTerminal');
    Route::get('terminals/needApproveList', 'TerminalController@needApproveList')->name('terminals.needApproveList');
    Route::get('terminals/approvedList', 'TerminalController@approvedList')->name('terminals.approvedList');
    Route::get('terminals/deniedList', 'TerminalController@deniedList')->name('terminals.deniedList');
    Route::get('terminals/lockedList', 'TerminalController@lockedList')->name('terminals.lockedList');
    Route::get('terminals/ajaxListMerchant', 'TerminalController@ajaxListMerchant')->name('terminals.ajaxListMerchant');
    Route::get('terminals/ajaxListMerchantWithAll', 'TerminalController@ajaxListMerchantWithAll')->name('terminals.ajaxListMerchantWithAll');
    Route::get('terminals/ajaxListTerminalByMerchantCode', 'TerminalController@ajaxListTerminalByMerchantCode')->name('terminals.ajaxListTerminalByMerchantCode');

    Route::get('terminals/ajaxFindBankAccount', 'TerminalController@ajaxFindBankAccount')->name('terminals.ajaxFindBankAccount');
    Route::post('stores/lockTerminal', 'TerminalController@lockTerminal')->name('terminals.lockTerminal');
    Route::post('stores/unlockTerminal', 'TerminalController@unlockTerminal')->name('terminals.unlockTerminal');

    Route::resource('terminals', 'TerminalController')->middleware('auth');

    Route::resource('terminalBatches', 'MpTerminalBatchController')->middleware('auth');
    Route::post('terminalBatches/{id}/reject', 'MpTerminalBatchController@reject')->name('terminalBatches.reject');
    Route::get('terminalBatches/{id}/approve', 'MpTerminalBatchController@approve')->name('terminalBatches.approve');
    Route::get('terminalBatches/{id}/reopenForEditTerminals', 'MpTerminalBatchController@reopenForEditTerminals')
        ->name('terminalBatches.reopenForEditTerminals');

    // enjoyments
    Route::get('enjoyments/changeEnjoyment', 'EnjoymentsController@changeEnjoyment')->name('enjoyments.changeEnjoyment');
    Route::get('enjoyments/index', 'EnjoymentsController@index')->name('enjoyments.index');
    Route::get('enjoyments/chooseMerchant', 'EnjoymentsController@chooseMerchant')->name('enjoyments.chooseMerchant');
    Route::post('enjoyments/chooseMerchant', 'EnjoymentsController@chooseMerchant')->name('enjoyments.chooseMerchant');
    Route::post('enjoyments/upsertEnjoyment', 'EnjoymentsController@upsertEnjoyment')->name('enjoyments.upsertEnjoyment');
    Route::get('enjoyments/ajaxFindBankAccount', 'EnjoymentsController@ajaxFindBankAccount')->name('enjoyments.ajaxFindBankAccount');
    Route::resource('enjoyments', 'EnjoymentsController')->middleware('auth');

    Route::resource('smsLogs', 'SmsLogController')->middleware('auth');

    Route::resource('users', 'UserController');

    Route::resource('roles', 'RoleController');

    Route::resource('permissions', 'PermissionController');

    Route::resource('mp_mid_tid_user', 'MpMidTidUserController');

    Route::get('mp_user/ajaxListPhone', 'MpUserController@ajaxListUserWithPhone')->name('mp_users.ajaxListUserWithPhone');



    Route::get('/api/get_districts_from_province_code',
        'API\ContentController@get_districts_from_province_code'
    );
    Route::get('/api/get_wards_from_district_code_and_province_code',
        'API\ContentController@get_wards_from_district_code_and_province_code'
    );
    Route::get('/api/get_staff_from_department',
        'API\ContentController@get_staff_from_department'
    );
    Route::get('/api/get_audit_logs',
        'API\ContentController@get_audit_logs'
    );
    Route::get('/api/search_merchant_users',
        'API\ContentController@search_merchant_users'
    );
    Route::get('/api/get_latest_terminal_of_merchant',
        'API\ContentController@get_latest_terminal_of_merchant'
    );
    Route::get('/api/get_combine_info_mer_ter',
        'API\ContentController@get_combine_info_mer_ter'
    );
    Route::get('/api/clear_filter',
        'API\ContentController@clearFilter'
    );


    Route::resource('messages', 'MessageController');
    Route::resource('utils', 'UtilController');
    Route::post('utils/resetUsers', 'UtilController@resetUsers')->name('utils.resetUsers');
    Route::resource('banners', 'BannerController');
});

app/Models/SmsLog.php
<?php

namespace App;

use Eloquent as Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Class SmsLog
 * @package App
 * @version December 17, 2019, 2:30 am UTC
 *
 * @property string phone
 * @property string message
 * @property string status
 * @property string error_code
 * @property string error_message
 */
class SmsLog extends Model
{
//    use SoftDeletes;

    public $table = 'sms_logs';
    
    const CREATED_AT = 'created_at';
    const UPDATED_AT = 'updated_at';


//    protected $dates = ['deleted_at'];

    public $connection = "rest_api_db";

    public $fillable = [
        'phone',
        'message',
        'status',
        'error_code',
        'error_message'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'phone' => 'string',
        'message' => 'string',
        'status' => 'string',
        'error_code' => 'string',
        'error_message' => 'string'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        'phone' => 'required',
        'message' => 'required'
    ];

    
}

app/Http/Controllers/SmsLogController.php
<?php

namespace App\Http\Controllers;

use App\DataTables\SmsLogDataTable;
use App\Http\Requests;
use App\Http\Requests\CreateSmsLogRequest;
use App\Http\Requests\UpdateSmsLogRequest;
use App\Repositories\SmsLogRepository;
use Flash;
use App\Http\Controllers\AppBaseController;
use Response;

class SmsLogController extends AppBaseController
{
    /** @var  SmsLogRepository */
    private $smsLogRepository;

    public function __construct(SmsLogRepository $smsLogRepo)
    {
        $this->smsLogRepository = $smsLogRepo;
    }

    /**
     * Display a listing of the SmsLog.
     *
     * @param SmsLogDataTable $smsLogDataTable
     * @return Response
     */
    public function index(SmsLogDataTable $smsLogDataTable)
    {
        return $smsLogDataTable->render('sms_logs.index');
    }

    /**
     * Show the form for creating a new SmsLog.
     *
     * @return Response
     */
    public function create()
    {
        return view('sms_logs.create');
    }

    /**
     * Store a newly created SmsLog in storage.
     *
     * @param CreateSmsLogRequest $request
     *
     * @return Response
     */
    public function store(CreateSmsLogRequest $request)
    {
        $input = $request->all();

        $smsLog = $this->smsLogRepository->create($input);

        Flash::success('Sms Log saved successfully.');

        return redirect(route('smsLogs.index'));
    }

    /**
     * Display the specified SmsLog.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $smsLog = $this->smsLogRepository->find($id);

        if (empty($smsLog)) {
            Flash::error('Sms Log not found');

            return redirect(route('smsLogs.index'));
        }

        return view('sms_logs.show')->with('smsLog', $smsLog);
    }

    /**
     * Show the form for editing the specified SmsLog.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $smsLog = $this->smsLogRepository->find($id);

        if (empty($smsLog)) {
            Flash::error('Sms Log not found');

            return redirect(route('smsLogs.index'));
        }

        return view('sms_logs.edit')->with('smsLog', $smsLog);
    }

    /**
     * Update the specified SmsLog in storage.
     *
     * @param  int              $id
     * @param UpdateSmsLogRequest $request
     *
     * @return Response
     */
    public function update($id, UpdateSmsLogRequest $request)
    {
        $smsLog = $this->smsLogRepository->find($id);

        if (empty($smsLog)) {
            Flash::error('Sms Log not found');

            return redirect(route('smsLogs.index'));
        }

        $smsLog = $this->smsLogRepository->update($request->all(), $id);

        Flash::success('Sms Log updated successfully.');

        return redirect(route('smsLogs.index'));
    }

    /**
     * Remove the specified SmsLog from storage.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function destroy($id)
    {
        $smsLog = $this->smsLogRepository->find($id);

        if (empty($smsLog)) {
            Flash::error('Sms Log not found');

            return redirect(route('smsLogs.index'));
        }

        $this->smsLogRepository->delete($id);

        Flash::success('Sms Log deleted successfully.');

        return redirect(route('smsLogs.index'));
    }
}

resources/views/sms_logs/create.blade.php
@extends('layouts_mms.app')

@section('content')
    @include('layouts_mms.page_header', ['header' => 'Thêm mới SMS', 'buttons' => [['title' => 'Quay lại', 'link' => route('smsLogs.index'), 'icon' => 'fa fa-arrow-left']]])
    @include('coreui-templates::common.errors')
    <div class="row">
        {!! Form::open(['route' => 'smsLogs.store']) !!}

        @include('sms_logs.fields')

        {!! Form::close() !!}
    </div>
@endsection

resources/views/sms_logs/datatables_actions.blade.php
{!! Form::open(['route' => ['smsLogs.destroy', $id],
'id' => 'delete_form_'.$id,
'method' => 'delete',
'onsubmit' => 'return confirm("Bạn chắc chắn thực hiện thao tác?")']) !!}
<div class="hidden-sm hidden-xs action-buttons">
    <a class="blue" href="{{ route('smsLogs.show', $id) }}">
        <i class="ace-icon fa fa-search-plus bigger-130"></i>
    </a>
    {{--<a class="green" href="{{ route('smsLogs.edit', $id) }}">--}}
        {{--<i class="ace-icon fa fa-pencil bigger-130"></i>--}}
    {{--</a>--}}

    {{--<a class="red" href="javascript:$('#{{'delete_form_'.$id}}').submit();">--}}
        {{--<i class="ace-icon fa fa-trash-o bigger-130" onclick=""></i>--}}
    {{--</a>--}}
</div>
{!! Form::close() !!}

resources/views/sms_logs/edit.blade.php
@extends('layouts_mms.app')

@section('content')
    @include('layouts_mms.page_header', ['header' => 'Cập nhật SMS', 'buttons' => [['title' => 'Quay lại', 'link' => route('smsLogs.index'), 'icon' => 'fa fa-arrow-left']]])
    @include('coreui-templates::common.errors')
    <div class="row">
        {!! Form::model($smsLog, ['route' => ['smsLogs.update', $smsLog->id], 'method' => 'patch']) !!}

        @include('sms_logs.fields')

        {!! Form::close() !!}
    </div>
@endsection

resources/views/sms_logs/fields.blade.php
<div class="col-md-6">
    <!-- Phone Field -->
    <div class="form-group">
        {!! Form::label('phone', 'Phone:') !!}
        {!! Form::text('phone', null, ['class' => 'form-control']) !!}
    </div>

    <!-- Message Field -->
    <div class="form-group">
        {!! Form::label('message', 'Nội dung:') !!}
        {!! Form::textarea('message', null, ['class' => 'form-control', 'rows' => 3, 'style' => 'height: 83px']) !!}
    </div>
</div>
<div class="col-md-6">
    <!-- Status Field -->
    <div class="form-group">
        {!! Form::label('status', 'Trạng thái:') !!}
        {!! Form::text('status', null, ['class' => 'form-control']) !!}
    </div>

    <!-- Error Code Field -->
    <div class="form-group">
        {!! Form::label('error_code', 'Mã lỗi:') !!}
        {!! Form::text('error_code', null, ['class' => 'form-control']) !!}
    </div>

    <!-- Error Message Field -->
    <div class="form-group">
        {!! Form::label('error_message', 'Mô tả lỗi:') !!}
        {!! Form::text('error_message', null, ['class' => 'form-control']) !!}
    </div>
</div>
<div class="col-md-12 text-center">
    <!-- Submit Field -->
    <div class="form-group">
        {!! Form::submit('Lưu', ['class' => 'btn btn-primary']) !!}
        <a href="{{ route('smsLogs.index') }}" class="btn btn-secondary">Quay lại</a>
    </div>
</div>

resources/views/sms_logs/index.blade.php
@extends('layouts_mms.app')

@section('content')
    @include('layouts_mms.page_header', ['header' => 'SMS Logging'])
    @include('flash::message')
    <div class="row dataTables_filter ">
        <div class="col-sm-3 form-group">
            <label>Tìm kiếm:</label>
            <input id="filter_query" class="form-control" placeholder="-- Nhập từ khóa tìm kiếm --">
        </div>
        <div class="col-sm-3 form-group">
            <label>Thời gian:</label>
            <input class="form-control drp" id="date_range_search" placeholder="-- Chọn ngày tìm kiếm --">
        </div>

        {{--<div class="col-sm-3 form-group">--}}
            {{--<label>Trạng thái:</label>--}}
            {{--<select id="filter_status" name="filter_status" class="form-control select2" data-placeholder="-- Chọn trạng thái --">--}}
                {{--<option></option>--}}
                {{--<option value="-1">--}}
                    {{--Khởi tạo--}}
                {{--</option>--}}
                {{--<option value="-2">--}}
                    {{--Khởi tạo lại--}}
                {{--</option>--}}
                {{--<option value="0">--}}
                    {{--Chờ duyệt--}}
                {{--</option>--}}
                {{--<option value="1">--}}
                    {{--Kinh doanh duyệt--}}
                {{--</option>--}}
                {{--<option value="2">--}}
                    {{--Đối soát duyệt--}}
                {{--</option>--}}
                {{--<option value="3">--}}
                    {{--Kinh doanh từ chối--}}
                {{--</option>--}}
                {{--<option value="4">--}}
                    {{--Đối soát từ chối--}}
                {{--</option>--}}
            {{--</select>--}}
        {{--</div>--}}
    </div>
    <div class="row">
        <div class="col-xs-12">
            @include('sms_logs.table')
        </div>
    </div>
@endsection

resources/views/sms_logs/show.blade.php
@extends('layouts_mms.app')

@section('content')
    @include('layouts_mms.page_header', ['header' => 'Chi tiết SMS', 'buttons' => [['title' => 'Quay lại', 'link' => route('smsLogs.index'), 'icon' => 'fa fa-arrow-left']]])
    @include('coreui-templates::common.errors')
    <div class="row">
        @include('sms_logs.show_fields')
    </div>
@endsection

resources/views/sms_logs/show_fields.blade.php
<div class="col-md-6">
    <!-- Phone Field -->
    <div class="form-group">
        {!! Form::label('phone', 'Phone:') !!}
        <p>{{ $smsLog->phone }}</p>
    </div>

    <!-- Message Field -->
    <div class="form-group">
        {!! Form::label('message', 'Message:') !!}
        <p>{{ $smsLog->message }}</p>
    </div>
</div>
<div class="col-md-6">
    <!-- Status Field -->
    <div class="form-group">
        {!! Form::label('status', 'Status:') !!}
        <p>{{ $smsLog->status }}</p>
    </div>

    <!-- Error Code Field -->
    <div class="form-group">
        {!! Form::label('error_code', 'Error Code:') !!}
        <p>{{ $smsLog->error_code }}</p>
    </div>

    <!-- Error Message Field -->
    <div class="form-group">
        {!! Form::label('error_message', 'Error Message:') !!}
        <p>{{ $smsLog->error_message }}</p>
    </div>
</div>

resources/views/sms_logs/table.blade.php
@section('css')
    @include('layouts_mms.datatables_css')
    @include('layouts_mms.daterange_picker_css')
@endsection

{!! $dataTable->table(['width' => '100%', 'class' => 'table table-striped table-bordered']) !!}

@section('scripts')
    @include('layouts_mms.daterange_picker_js', ['init_id' => ['date_range_search']])
    @include('layouts_mms.datatables_js')
    {!! $dataTable->scripts() !!}
    <script>
        var queryTypingTimer;
        var doneTypingInterval = 1000;
        var $input = $('#filter_query');
        $input.on('keyup', function () {
            clearTimeout(queryTypingTimer);
            queryTypingTimer = setTimeout(doneFilterTyping, doneTypingInterval);
        });
        $input.on('keydown', function () {
            clearTimeout(queryTypingTimer);
        });
        function doneFilterTyping () {
            if (window.LaravelDataTables && window.LaravelDataTables['dataTableBuilder']){
                window.LaravelDataTables['dataTableBuilder'].search($input.val()).draw();
            }
        }
        $('#filter_status').on('change', function () {
            if (window.LaravelDataTables && window.LaravelDataTables['dataTableBuilder']){
                window.LaravelDataTables['dataTableBuilder'].columns(2).search($(this).val()).draw();
            }
        });
    </script>
@endsection